# Generated by Django 4.2.4 on 2023-08-27 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code3", models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name="Cource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course", models.DecimalField(decimal_places=4, max_digits=16)),
                ("update_time", models.DateTimeField()),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.currency"
                    ),
                ),
            ],
        ),
    ]
