# Generated by Django 4.2.4 on 2023-08-27 12:14
# And updated by FalseR

from datetime import datetime
from decimal import Decimal

from django.db import migrations


def create_courses(apps, schema_editor):
    Currency = apps.get_model('core', 'Currency')
    Cource = apps.get_model('core', 'Cource')
    now = datetime.now()
    Cource(currency=Currency.objects.get(code3="BYN"), course=Decimal("1.0000"), update_time=now).save()
    Cource(currency=Currency.objects.get(code3="USD"), course=Decimal("3.0000"), update_time=now).save()
    Cource(currency=Currency.objects.get(code3="EUR"), course=Decimal("3.1000"), update_time=now).save()
    Cource(currency=Currency.objects.get(code3="RUB"), course=Decimal("0.0335"), update_time=now).save()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_default_currencies"),
    ]

    operations = [
        migrations.RunPython(create_courses)
    ]
